<a href="https://colab.research.google.com/github/karuego/SIC-Batch5/blob/main/W1_P1_Python_for_AI%2C_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np
import pandas as pd

## List and Array Performance Comparison

Before we jump in, let's check list and array computation time

In [ ]:
l = list(range(1000000))
a = np.arange(10000000)

print(l)
print(a)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
%time np.sum(a ** 2)

CPU times: user 1.02 ms, sys: 1 µs, total: 1.02 ms
Wall time: 1.17 ms


333328333350000

In [ ]:
%time sum([x ** 2 for x in l])

CPU times: user 31.5 ms, sys: 3.99 ms, total: 35.5 ms
Wall time: 37.4 ms


333328333350000

---
Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

## Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
my_matrix * 2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.array(my_matrix)*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.array(my_matrix).dtype

dtype('int64')

In [ ]:
c = np.array([1, 2.0, 3])
print(c)
print(c.dtype)

[1. 2. 3.]
float64


In [ ]:
np.random.rand(2)

array([0.56224426, 0.61661102])

In [ ]:
np.random.rand(5,5)

array([[0.83147161, 0.95775041, 0.5643127 , 0.45690319, 0.35891455],
       [0.38705312, 0.45252009, 0.72974705, 0.75727892, 0.20278781],
       [0.6194628 , 0.74993029, 0.5754149 , 0.99134575, 0.4435996 ],
       [0.31671341, 0.86795413, 0.91041619, 0.72520115, 0.97736045],
       [0.52666752, 0.91548616, 0.06966299, 0.52856098, 0.45108406]])

---
## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,100, 2)
ranarr

array([65, 55])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([23, 47, 35, 32, 43, 29, 19, 45, 20, 30])

In [ ]:
# ranarr = np.random.randint(0,100, 2)
arr = np.arange(12)
print(arr)
arr.reshape(2,3,2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
ranarr = np.random.randint(0,100,5)
ranarr

array([66, 43, 31, 99, 20])

In [ ]:
ranarr.max()

99

In [ ]:
np.max(ranarr)

99

In [ ]:
ranarr.argmax()

3

In [ ]:
ranarr.min()

20

In [ ]:
ranarr.argmin()

4

---
## Dimensions and Shapes

`ndim`, `size`, and `shape`

- Shape is an attribute that arrays have (not a method)
- `ndim` returns the array dimension
- `size` returns the number of elements in the array

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [ ]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

# NumPy Indexing and Selection

## Bracket Indexing and Selection

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Get a value at an index
arr[8]

8

In [ ]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
#Get values in a range
arr[-4:]

array([ 7,  8,  9, 10])

In [ ]:
#Get values in a range
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[0:]

In [ ]:
arr[1:3]

In [ ]:
arr[1:-1]

In [ ]:
print(arr)
arr[::5]

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 0,  5, 10])

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Indexing a 2D array (matrices)

The general format are:
- **arr_2d[row][col]** or
- **arr_2d[row,col]**.

I recommend usually using the comma notation for clarity.

Similar with Python List, array index also start from 0

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# Getting individual element value
arr_2d[1,0]

20

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

In [ ]:
#Shape bottom row
arr_2d[2]

In [ ]:
#Shape bottom row
arr_2d[2,:]

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
arr > 4

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr<6]

In [ ]:
x = 2
arr[arr>x]

# NumPy Operations

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr

In [ ]:
arr + arr

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
arr.sum()

In [ ]:
arr.mean()

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A.sum()

In [ ]:
A.mean()

In [ ]:
A.sum(axis=1)

In [ ]:
A.sum(axis=0)

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A.dot(B), A @ B

In [ ]:
B.T

# Introduction to Pandas

In this section of the course we will learn how to use pandas for data analysis. Think of pandas as an extremely powerful version of Excel, with a lot more features. In this section of the course, you should go through the notebooks in this order:

* Introduction to Pandas
* Series
* DataFrames
* Summary Functions and Aggregation (GroupBy)
* Combining Data - Merging, Joining, and Concatenating (Optional)
* Operations
* Data Input and Output
___

In [ ]:
# Importing required libraries and fixing options
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.options.display.max_columns = None
pd.options.display.max_rows = None

%matplotlib inline

## Let's explore some COVID19 data available online using basic **Pandas functions**:
[Reference](https://ourworldindata.org/coronavirus/country/indonesia)

In [ ]:
# Importing the data from file
covid_df = pd.read_csv('https://covid.ourworldindata.org/data/owid-covid-data.csv')


# Let's see a sample of the data
covid_df.head(10) # top 5 rows

iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  2020-01-05          NaN        0.0   
1      AFG      Asia  Afghanistan  2020-01-06          NaN        0.0   
2      AFG      Asia  Afghanistan  2020-01-07          NaN        0.0   
3      AFG      Asia  Afghanistan  2020-01-08          NaN        0.0   
4      AFG      Asia  Afghanistan  2020-01-09          NaN        0.0   
5      AFG      Asia  Afghanistan  2020-01-10          NaN        0.0   
6      AFG      Asia  Afghanistan  2020-01-11          NaN        0.0   
7      AFG      Asia  Afghanistan  2020-01-12          NaN        0.0   
8      AFG      Asia  Afghanistan  2020-01-13          NaN        0.0   
9      AFG      Asia  Afghanistan  2020-01-14          NaN        0.0   

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
0                 NaN           NaN         0.0                  NaN   
1                 NaN           NaN         0.0                  NaN   
2                 NaN           NaN         0.0                  NaN   
3                 NaN           NaN         0.0                  NaN   
4                 NaN           NaN         0.0                  NaN   
5                 0.0           NaN         0.0                  0.0   
6                 0.0           NaN         0.0                  0.0   
7                 0.0           NaN         0.0                  0.0   
8                 0.0           NaN         0.0                  0.0   
9                 0.0           NaN         0.0                  0.0   

   total_cases_per_million  new_cases_per_million  \
0                      NaN                    0.0   
1                      NaN                    0.0   
2                      NaN                    0.0   
3                      NaN                    0.0   
4                      NaN                    0.0   
5                      NaN                    0.0   
6                      NaN                    0.0   
7                      NaN                    0.0   
8                      NaN                    0.0   
9                      NaN                    0.0   

   new_cases_smoothed_per_million  total_deaths_per_million  \
0                             NaN                       NaN   
1                             NaN                       NaN   
2                             NaN                       NaN   
3                             NaN                       NaN   
4                             NaN                       NaN   
5                             0.0                       NaN   
6                             0.0                       NaN   
7                             0.0                       NaN   
8                             0.0                       NaN   
9                             0.0                       NaN   

   new_deaths_per_million  new_deaths_smoothed_per_million  reproduction_rate  \
0                     0.0                              NaN                NaN   
1                     0.0                              NaN                NaN   
2                     0.0                              NaN                NaN   
3                     0.0                              NaN                NaN   
4                     0.0                              NaN                NaN   
5                     0.0                              0.0                NaN   
6                     0.0                              0.0                NaN   
7                     0.0                              0.0                NaN   
8                     0.0                              0.0                NaN   
9                     0.0                              0.0                NaN   

   icu_patients  icu_patients_per_million  hosp_patients  \
0           NaN                       NaN            NaN   
1           NaN                       NaN            NaN   
2           NaN                       NaN            Na

In [ ]:
covid_df.tail(10) #last 10 rows

iso_code continent  location        date  total_cases  new_cases  \
400990      ZWE    Africa  Zimbabwe  2024-05-03     266362.0        0.0   
400991      ZWE    Africa  Zimbabwe  2024-05-04     266362.0        0.0   
400992      ZWE    Africa  Zimbabwe  2024-05-05     266362.0        0.0   
400993      ZWE    Africa  Zimbabwe  2024-05-06     266362.0        0.0   
400994      ZWE    Africa  Zimbabwe  2024-05-07     266362.0        0.0   
400995      ZWE    Africa  Zimbabwe  2024-05-08     266362.0        0.0   
400996      ZWE    Africa  Zimbabwe  2024-05-09     266362.0        0.0   
400997      ZWE    Africa  Zimbabwe  2024-05-10     266362.0        0.0   
400998      ZWE    Africa  Zimbabwe  2024-05-11     266362.0        0.0   
400999      ZWE    Africa  Zimbabwe  2024-05-12     266362.0        0.0   

        new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
400990               0.429        5740.0         0.0                  0.0   
400991               0.429        5740.0         0.0                  0.0   
400992               0.000        5740.0         0.0                  0.0   
400993               0.000        5740.0         0.0                  0.0   
400994               0.000        5740.0         0.0                  0.0   
400995               0.000        5740.0         0.0                  0.0   
400996               0.000        5740.0         0.0                  0.0   
400997               0.000        5740.0         0.0                  0.0   
400998               0.000        5740.0         0.0                  0.0   
400999               0.000        5740.0         0.0                  0.0   

        total_cases_per_million  new_cases_per_million  \
400990                16320.662                    0.0   
400991                16320.662                    0.0   
400992                16320.662                    0.0   
400993                16320.662                    0.0   
400994                16320.662                    0.0   
400995                16320.662                    0.0   
400996                16320.662                    0.0   
400997                16320.662                    0.0   
400998                16320.662                    0.0   
400999                16320.662                    0.0   

        new_cases_smoothed_per_million  total_deaths_per_million  \
400990                           0.026                   351.704   
400991                           0.026                   351.704   
400992                           0.000                   351.704   
400993                           0.000                   351.704   
400994                           0.000                   351.704   
400995                           0.000                   351.704   
400996                           0.000                   351.704   
400997                           0.000                   351.704   
400998                           0.000                   351.704   
400999                           0.000                   351.704   

        new_deaths_per_million  new_deaths_smoothed_per_million  \
400990                     0.0                              0.0   
400991                     0.0                              0.0   
400992                     0.0                              0.0   
400993                     0.0                              0.0   
400994                     0.0                              0.0   
400995                     0.0                              0.0   
400996                     0.0                              0.0   
400997                     0.0                              0.0   
400998                     0.0                              0.0   
400999                     0.0                              0.0   

        reproduction_rate  icu_patients  icu_patients_per_million  \
400990                NaN           NaN                       NaN   
400991                NaN           NaN                       NaN   


In [ ]:
covid_df.sample(10, random_state=111) #Sample 10 rows randomly selected from the data

iso_code      continent           location        date  total_cases  \
284294      POL         Europe             Poland  2020-03-06          NaN   
326655      SVK         Europe           Slovakia  2023-10-03    1867525.0   
52952       BGR         Europe           Bulgaria  2021-04-06     352259.0   
174425      JAM  North America            Jamaica  2023-05-28     154965.0   
296805      RWA         Africa             Rwanda  2023-12-17     133208.0   
269827      OMN           Asia               Oman  2024-02-07     399449.0   
218762      MTQ  North America         Martinique  2020-08-17        336.0   
12641       AIA  North America           Anguilla  2024-02-24       3904.0   
103228      GNQ         Africa  Equatorial Guinea  2020-02-25          NaN   
158026      HUN         Europe            Hungary  2022-02-05    1508358.0   

        new_cases  new_cases_smoothed  total_deaths  new_deaths  \
284294        0.0               0.000           NaN         0.0   
326655        0.0              14.857       21167.0         0.0   
52952         0.0            3498.429       13507.0         0.0   
174425       39.0               5.571        3540.0         2.0   
296805        0.0               0.000        1468.0         0.0   
269827        0.0               0.000        4628.0         0.0   
218762        0.0               0.000          16.0         0.0   
12641         0.0               0.000          12.0         0.0   
103228        0.0               0.000           NaN         0.0   
158026        0.0           15271.571       41229.0         0.0   

        new_deaths_smoothed  total_cases_per_million  new_cases_per_million  \
284294                0.000                      NaN                  0.000   
326655                0.000               330918.737                  0.000   
52952               122.429                51940.628                  0.000   
174425                0.286                54808.653                 13.794   
296805                0.000                 9669.078                  0.000   
269827                0.000                87286.454                  0.000   
218762                0.000                  914.256                  0.000   
12641                 0.000               245890.282                  0.000   
103228                0.000                      NaN                  0.000   
158026               58.143               151330.590                  0.000   

        new_cases_smoothed_per_million  total_deaths_per_million  \
284294                           0.000                       NaN   
326655                           2.633                  3750.717   
52952                          515.844                  1991.609   
174425                           1.971                  1252.042   
296805                           0.000                   106.557   
269827                           0.000                  1011.297   
218762                           0.000                    43.536   
12641                            0.000                   755.810   
103228                           0.000                       NaN   
158026                        1532.167                  4136.424   

        new_deaths_per_million  new_deaths_smoothed_per_million  \
284294                   0.000                            0.000   
326655                   0.000                            0.000   
52952                    0.000                           18.052   
174425                   0.707                            0.101   
296805                   0.000                            0.000   
269827                   0.000                            0.000   
218762                   0.000                            0.000   
12641                    0.000                            0.000   
103228                   0.000                            0.000   
158026                   0.000                            5.833   

        reproduction_rate  icu_patients  icu_patients

In [ ]:
covid_df['location'].value_counts()

location
Malaysia                            1602
Asia                                1602
Europe                              1602
Czechia                             1602
High income                         1602
India                               1602
Upper middle income                 1602
European Union                      1602
World                               1602
Lithuania                           1602
Lower middle income                 1602
Greece                              1601
Bulgaria                            1601
Italy                               1600
North America                       1600
Canada                              1600
Bangladesh                          1599
Netherlands                         1599
Estonia                             1598
New Zealand                         1595
Oceania                             1595
Argentina                           1594
Mexico                              1594
Thailand                            1591
Portuga

In [ ]:
covid_df.shape

(401000, 67)

In [ ]:
interested_countries_list = ['India','Indonesia']

covid_df1 = covid_df[
    covid_df['location'].isin(interested_countries_list)
]

In [ ]:
covid_df1.head()

iso_code continent location        date  total_cases  new_cases  \
160444      IND      Asia    India  2020-01-05          NaN        0.0   
160445      IND      Asia    India  2020-01-06          NaN        0.0   
160446      IND      Asia    India  2020-01-07          NaN        0.0   
160447      IND      Asia    India  2020-01-08          NaN        0.0   
160448      IND      Asia    India  2020-01-09          NaN        0.0   

        new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
160444                 NaN           NaN         0.0                  NaN   
160445                 NaN           NaN         0.0                  NaN   
160446                 NaN           NaN         0.0                  NaN   
160447                 NaN           NaN         0.0                  NaN   
160448                 NaN           NaN         0.0                  NaN   

        total_cases_per_million  new_cases_per_million  \
160444                      NaN                    0.0   
160445                      NaN                    0.0   
160446                      NaN                    0.0   
160447                      NaN                    0.0   
160448                      NaN                    0.0   

        new_cases_smoothed_per_million  total_deaths_per_million  \
160444                             NaN                       NaN   
160445                             NaN                       NaN   
160446                             NaN                       NaN   
160447                             NaN                       NaN   
160448                             NaN                       NaN   

        new_deaths_per_million  new_deaths_smoothed_per_million  \
160444                     0.0                              NaN   
160445                     0.0                              NaN   
160446                     0.0                              NaN   
160447                     0.0                              NaN   
160448                     0.0                              NaN   

        reproduction_rate  icu_patients  icu_patients_per_million  \
160444                NaN           NaN                       NaN   
160445                NaN           NaN                       NaN   
160446                NaN           NaN                       NaN   
160447                NaN           NaN                       NaN   
160448                NaN           NaN                       NaN   

        hosp_patients  hosp_patients_per_million  weekly_icu_admissions  \
160444            NaN                        NaN                    NaN   
160445            NaN                        NaN                    NaN   
160446            NaN                        NaN                    NaN   
160447            NaN                        NaN                    NaN   
160448            NaN                        NaN                    NaN   

        weekly_icu_admissions_per_million  weekly_hosp_admissions  \
160444                                NaN                     NaN   
160445                                NaN                     NaN   
160446                                NaN                     NaN   
160447                                NaN                     NaN   
160448                                NaN                     NaN   

        weekly_hosp_admissions_per_million  total_tests  new_tests  \
160444                                 NaN          NaN        NaN   
160445                                 NaN          NaN        NaN   
160446                                 NaN          NaN        NaN   
160447                                 NaN          NaN        NaN   
160448                                 NaN          NaN        NaN   

        total_tests_per_thousand  new_tests_per_thousand  new_tests_smoothed  \
160444                       NaN                     NaN                 NaN   
160445                       NaN                     NaN                 NaN

In [ ]:
covid_df1["location"].unique()

array(['India', 'Indonesia'], dtype=object)

In [ ]:
covid_df1.head()

# slicing cara 1
slicing_1 = covid_df1[["iso_code", "continent"]].head()

#cara 2
slicing_2 = covid_df1["iso_code"].head()

# cara 3
slicing_3 = covid_df1.iso_code.head()

display(slicing_1)
display(slicing_2)
display(slicing_3)

iso_code continent
160444      IND      Asia
160445      IND      Asia
160446      IND      Asia
160447      IND      Asia
160448      IND      Asia

160444    IND
160445    IND
160446    IND
160447    IND
160448    IND
Name: iso_code, dtype: object

160444    IND
160445    IND
160446    IND
160447    IND
160448    IND
Name: iso_code, dtype: object

In [ ]:
covid_df.iloc[: , :2].head()

iso_code continent
0      AFG      Asia
1      AFG      Asia
2      AFG      Asia
3      AFG      Asia
4      AFG      Asia

In [ ]:
covid_df[covid_df.location == 'Indonesia'].sample(5)

iso_code continent   location        date  total_cases  new_cases  \
162835      IDN      Asia  Indonesia  2022-03-04    5539394.0        0.0   
162802      IDN      Asia  Indonesia  2022-01-30    4343185.0    56807.0   
163304      IDN      Asia  Indonesia  2023-06-16    6810119.0        0.0   
163581      IDN      Asia  Indonesia  2024-03-19    6828884.0        0.0   
163471      IDN      Asia  Indonesia  2023-11-30    6813429.0        0.0   

        new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
162835           48841.286      148073.0         0.0              244.000   
162802            8115.286      144303.0        83.0               11.857   
163304             226.000      161821.0         0.0                4.571   
163581               4.000      162056.0         0.0                0.000   
163471               0.000      161918.0         0.0                0.000   

        total_cases_per_million  new_cases_per_million  \
162835                20106.595                  0.000   
162802                15764.660                206.195   
163304                24719.005                  0.000   
163581                24787.117                  0.000   
163471                24731.019                  0.000   

        new_cases_smoothed_per_million  total_deaths_per_million  \
162835                         177.281                   537.467   
162802                          29.456                   523.783   
163304                           0.820                   587.369   
163581                           0.015                   588.222   
163471                           0.000                   587.721   

        new_deaths_per_million  new_deaths_smoothed_per_million  \
162835                   0.000                            0.886   
162802                   0.301                            0.043   
163304                   0.000                            0.017   
163581                   0.000                            0.000   
163471                   0.000                            0.000   

        reproduction_rate  icu_patients  icu_patients_per_million  \
162835               0.74           NaN                       NaN   
162802               2.29           NaN                       NaN   
163304                NaN           NaN                       NaN   
163581                NaN           NaN                       NaN   
163471                NaN           NaN                       NaN   

        hosp_patients  hosp_patients_per_million  weekly_icu_admissions  \
162835            NaN                        NaN                    NaN   
162802            NaN                        NaN                    NaN   
163304            NaN                        NaN                    NaN   
163581            NaN                        NaN                    NaN   
163471            NaN                        NaN                    NaN   

        weekly_icu_admissions_per_million  weekly_hosp_admissions  \
162835                                NaN                     NaN   
162802                                NaN                     NaN   
163304                                NaN                     NaN   
163581                                NaN                     NaN   
163471                                NaN                     NaN   

        weekly_hosp_admissions_per_million  total_tests  new_tests  \
162835                                 NaN   57117140.0   193981.0   
162802                                 NaN   48343446.0   205803.0   
163304                                 NaN          NaN        NaN   
163581                                 NaN          NaN        NaN   
163471                                 NaN          NaN        NaN   

        total_tests_per_thousand  new_tests_per_thousand  new_tests_smoothed  \
162835                   208.645                   0.709            213616.0   
162802                   176.595                   0.752        

In [ ]:
covid_df.to_csv('covid_data_output.csv', header=True, index=False)
# covid_df.to_

In [ ]:
covid_df1.describe(include="all")

iso_code continent location        date   total_cases     new_cases  \
count      3192      3192     3192        3192  3.089000e+03  3.180000e+03   
unique        2         1        2        1602           NaN           NaN   
top         IND      Asia    India  2020-01-05           NaN           NaN   
freq       1602      3192     1602           2           NaN           NaN   
mean        NaN       NaN      NaN         NaN  1.777156e+07  1.631054e+04   
std         NaN       NaN      NaN         NaN  1.819204e+07  1.289120e+05   
min         NaN       NaN      NaN         NaN  2.000000e+00  0.000000e+00   
25%         NaN       NaN      NaN         NaN  4.129020e+06  0.000000e+00   
50%         NaN       NaN      NaN         NaN  6.813429e+06  0.000000e+00   
75%         NaN       NaN      NaN         NaN  4.301945e+07  0.000000e+00   
max         NaN       NaN      NaN         NaN  4.503852e+07  2.738957e+06   

        new_cases_smoothed   total_deaths    new_deaths  new_deaths_smoothed  \
count          3170.000000    3040.000000   3179.000000          3169.000000   
unique                 NaN            NaN           NaN                  NaN   
top                    NaN            NaN           NaN                  NaN   
freq                   NaN            NaN           NaN                  NaN   
mean          16361.790988  250412.838816    218.830135           219.517968   
std           46388.354569  200547.036844   1509.741831           534.140774   
min               0.000000       2.000000      0.000000             0.000000   
25%             172.286000  122111.000000      0.000000             2.286000   
50%            1804.714000  161284.000000      0.000000            24.000000   
75%           10667.857000  521685.000000      0.000000           185.286000   
max          391279.571000  533599.000000  28982.000000          4140.286000   

        total_cases_per_million  new_cases_per_million  \
count               3089.000000            3180.000000   
unique                      NaN                    NaN   
top                         NaN                    NaN   
freq                        NaN                    NaN   
mean               18788.085344              17.788714   
std                11446.417969             111.212659   
min                    0.001000               0.000000   
25%                 6805.253000               0.000000   
50%                23436.793000               0.000000   
75%                30355.821000               0.000000   
max                31780.534000            1932.690000   

        new_cases_smoothed_per_million  total_deaths_per_million  \
count                      3170.000000               3040.000000   
unique                             NaN                       NaN   
top                                NaN                       NaN   
freq                               NaN                       NaN   
mean                         17.844685                339.663321   
std                          38.720757                201.906051   
min                           0.000000                  0.001000   
25%                           0.182000                131.273000   
50%                           3.428000                374.458000   
75%                          17.560000                564.883000   
max                         276.099000                588.229000   

        new_deaths_per_million  new_deaths_smoothed_per_million  \
count              3179.000000                      3169.000000   
unique                     NaN                              NaN   
top                        NaN                              NaN   
freq                       NaN                              NaN   
mean                  0.303483                         0.304446   
std                   2.072225                         0.732027   
min                   0.000000                         0.000000   
25%                   0.000000                         0.00

In [ ]:
covid_df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3192 entries, 160444 to 163635
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype  
---  ------                                      --------------  -----  
 0   iso_code                                    3192 non-null   object 
 1   continent                                   3192 non-null   object 
 2   location                                    3192 non-null   object 
 3   date                                        3192 non-null   object 
 4   total_cases                                 3089 non-null   float64
 5   new_cases                                   3180 non-null   float64
 6   new_cases_smoothed                          3170 non-null   float64
 7   total_deaths                                3040 non-null   float64
 8   new_deaths                                  3179 non-null   float64
 9   new_deaths_smoothed                         3169 non-null   float64
 10  total_case

In [ ]:
covid_df1['total_cases'].mean()

In [ ]:
covid_df1.shape

In [ ]:
covid_df1['location'].value_counts()

## Data Aggregation

In [ ]:
# Create dataframe
data = {
    'Company':['SAMSUNG','SAMSUNG','SKILVUL','SKILVUL','FB','FB'],
    'Person':['Ayub','Amri','Calvin','Addie','Becca','Sara'],
    'Sales':[200,1200,340,124,243,350],
    'Margin':[40,40,34,100,56,60]
    }

In [ ]:
df = pd.DataFrame(data)
df

Company  Person  Sales  Margin
0  SAMSUNG    Ayub    200      40
1  SAMSUNG    Amri   1200      40
2  SKILVUL  Calvin    340      34
3  SKILVUL   Addie    124     100
4       FB   Becca    243      56
5       FB    Sara    350      60

In [ ]:
df.describe(include="all")

Company Person        Sales      Margin
count         6      6     6.000000    6.000000
unique        3      6          NaN         NaN
top     SAMSUNG   Ayub          NaN         NaN
freq          2      1          NaN         NaN
mean        NaN    NaN   409.500000   55.000000
std         NaN    NaN   396.581265   24.256958
min         NaN    NaN   124.000000   34.000000
25%         NaN    NaN   210.750000   40.000000
50%         NaN    NaN   291.500000   48.000000
75%         NaN    NaN   347.500000   59.000000
max         NaN    NaN  1200.000000  100.000000

**Now you can use the .groupby() method to group rows together based off of a column name**


For instance let's group based off of Company. This will create a *DataFrameGroupBy* object:

In [ ]:
df.groupby('Company')
#select company from df group by company

In [ ]:
# You can save this object as a new variable:
by_comp = df.groupby('Company')
print(by_comp)

In [ ]:
# And then call aggregate methods off the object:
display(df)
by_comp['Sales'].max()

Company  Person  Sales  Margin
0  SAMSUNG    Ayub    200      40
1  SAMSUNG    Amri   1200      40
2  SKILVUL  Calvin    340      34
3  SKILVUL   Addie    124     100
4       FB   Becca    243      56
5       FB    Sara    350      60

Company
FB          350
SAMSUNG    1200
SKILVUL     340
Name: Sales, dtype: int64

In [ ]:
# In one step:
df.groupby('Company')['Sales'].std()

Company
FB          75.660426
SAMSUNG    707.106781
SKILVUL    152.735065
Name: Sales, dtype: float64

**More examples of aggregate methods in pandas:**

In [ ]:
by_comp['Sales'].std()

In [ ]:
by_comp.min()

In [ ]:
by_comp.max()

In [ ]:
by_comp.count()

In [ ]:
by_comp.describe()

In [ ]:
display(df.groupby('Company')['Sales'].aggregate(['mean','sum','max','min']))

print()

df.groupby('Company')['Sales'].aggregate(['mean','sum','max','min']).transpose()

mean   sum   max  min
Company                        
FB       296.5   593   350  243
SAMSUNG  700.0  1400  1200  200
SKILVUL  232.0   464   340  124

Company     FB  SAMSUNG  SKILVUL
mean     296.5    700.0    232.0
sum      593.0   1400.0    464.0
max      350.0   1200.0    340.0
min      243.0    200.0    124.0

In [ ]:
by_comp.describe().transpose()

Company               FB      SAMSUNG     SKILVUL
Sales  count    2.000000     2.000000    2.000000
       mean   296.500000   700.000000  232.000000
       std     75.660426   707.106781  152.735065
       min    243.000000   200.000000  124.000000
       25%    269.750000   450.000000  178.000000
       50%    296.500000   700.000000  232.000000
       75%    323.250000   950.000000  286.000000
       max    350.000000  1200.000000  340.000000
Margin count    2.000000     2.000000    2.000000
       mean    58.000000    40.000000   67.000000
       std      2.828427     0.000000   46.669048
       min     56.000000    40.000000   34.000000
       25%     57.000000    40.000000   50.500000
       50%     58.000000    40.000000   67.000000
       75%     59.000000    40.000000   83.500000
       max     60.000000    40.000000  100.000000

In [ ]:
by_comp.describe().transpose()['SKILVUL']

In [ ]:
# Let's try some aggregagation on our COVID Data:
covid_df.groupby(['continent','location'])['new_cases'].aggregate(['count','mean','median']).sort_values('location')

## Operations on Pandas Columns
* Addition, Subtraction, etc.
* sort_values(), sort_index()
* Dropping columns
* Applying functions to Pandas Dataframes (Map and Apply)

### Column Operations

In [ ]:
temp_df = covid_df1 [['location',	'date', 'new_cases']].tail(10)
temp_df

In [ ]:
temp_df['new_cases_added'] = temp_df['new_cases'] + temp_df['new_cases']
temp_df

In [ ]:
temp_df['new_cases_twice'] = temp_df['new_cases'] *2

In [ ]:
temp_df.sort_values(by = ['new_cases','date'],ascending=[False,True], inplace=True)

In [ ]:
temp_df

In [ ]:
temp_df.sort_index(inplace=True)
temp_df

In [ ]:
temp_df.drop(['new_cases_added','new_cases_twice'],axis = 1)

In [ ]:
temp_df

In [ ]:
temp_df.drop(columns = ['new_cases_added','new_cases_twice'],inplace = True)

### Applying functions to Pandas dataframes
[Reference Link for Map and Apply](https://towardsdatascience.com/introduction-to-pandas-apply-applymap-and-map-5d3e044e93ff)

In [ ]:
temp_df

In [ ]:
# In-built Python method
temp_df['sqrt_new_cases'] = temp_df['new_cases'].apply(np.sqrt)
temp_df

Create a column as 'new_cases_category' which shows:
* <=40 Cases             -- 'Low'
* 40k+ to 50k Cases      -- 'Medium'
* Greater than 50k Cases -- 'High'

In [ ]:
# UDF - User defined function
def category_fn (number_of_cases):
  if number_of_cases<=40000: cat = 'Low'
  elif number_of_cases>50000: cat = 'High'
  else: cat = 'Medium'
  return cat

In [ ]:
category_fn (55000)

In [ ]:
temp_df['new_cases_category'] = temp_df['new_cases'].apply(category_fn)
temp_df

In [ ]:
temp_df['new_cases_category1'] = temp_df['new_cases'].map(category_fn)
temp_df

#### Comparing map, applymap and apply: **Context Matters**

[Reference Link](https://stackoverflow.com/questions/19798153/difference-between-map-applymap-and-apply-methods-in-pandas)

**First major difference: DEFINITION**

* `map` is defined on Series ONLY
* `applymap` is defined on DataFrames ONLY
* `apply` is defined on BOTH

**Second major difference: INPUT ARGUMENT**
* `map` accepts dicts, Series, or callable
* `applymap` and apply accept callables only

**Third major difference: BEHAVIOR**

* `map` is elementwise for Series
* `applymap` is elementwise for DataFrames
* `apply` also works elementwise but is suited to more complex operations and aggregation. The behaviour and return value depends on the function.

**Fourth major difference (the most important one): USE CASE**

* `map` is meant for mapping values from one domain to another, so is optimised for performance (e.g., df['A'].map({1:'a', 2:'b', 3:'c'}))
* `applymap` is good for elementwise transformations across multiple rows/columns (e.g., df[['A', 'B', 'C']].applymap(str.strip))
* `apply` is for applying any function that cannot be vectorised (e.g., df['sentences'].apply(nltk.sent_tokenize))

&nbsp;

**Summarizing:**
<img src="https://i.stack.imgur.com/IZys3.png">

> **Footnotes:**
1. `map` when passed a dictionary/Series will map elements based on the keys in that dictionary/Series. Missing values will be recorded as NaN in the output.
2. `applymap` in more recent versions has been optimised for some operations. You will find `applymap` slightly faster than apply in some cases. My suggestion is to test them both and use whatever works better.
3. `map` is optimised for elementwise mappings and transformation. Operations that involve dictionaries or Series will enable pandas to use faster code paths for better performance.
4. `Series.apply` returns a scalar for aggregating operations, Series otherwise. Similarly for `DataFrame.apply`. Note that `apply` also has fastpaths when called with certain NumPy functions such as `mean`, `sum`, etc.

## Merging, Joining, and Concatenating (Optional)

There are 3 main ways of combining DataFrames together: Merging, Joining and Concatenating. In this section we will discuss these 3 methods with examples.

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [ ]:
df1

In [ ]:
df2

In [ ]:
df3

### Concatenation
Concatenation basically glues together DataFrames. Keep in mind that dimensions should match along the axis you are concatenating on. You can use pd.concat and pass in a list of DataFrames to concatenate together:

In [ ]:
# Similar to Union of 2 or more tables in SQL
pd.concat([df1,df2,df3])

In [ ]:
pd.concat([df1,df2,df3],axis=1)

In [ ]:
df2.reset_index()

In [ ]:
pd.concat([df1,df2.reset_index(drop=True),df3.reset_index(drop=True)],axis=1)

### Merging

The **merge** function allows you to merge DataFrames together using a similar logic as joining SQL Tables together.

In [ ]:
df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
pd.merge(df1,df2,how='inner',on='key')

More complicated example:

In [ ]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
pd.merge(left, right, on=['key1', 'key2'])

In [ ]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

In [ ]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

In [ ]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

In [ ]:
pd.merge(left, right, how='inner', left_on = 'key1', right_on = 'key2')

### Joining
Joining is a convenient method for combining the columns of two potentially differently-indexed DataFrames into a single result DataFrame.

In [ ]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2'])

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [ ]:
left.join(right)

In [ ]:
left.join(right, how='outer')